//! Rust-backed JavaScript classes, mirroring `rquickjs::class`.
//!
//! Implement [`JsClass`] (normally through `#[rbun::class]` +
//! `#[rbun::methods]`), then `Class::<T>::define(&ctx.globals())` or
//! `Class::instance(ctx, value)`.
//!
//! Instances hold their Rust value in a `RefCell` behind the JS object's
//! private data; [`Class::borrow`] / [`Class::borrow_mut`] hand out guards.

use core::any::TypeId;
use core::cell::{Ref, RefCell, RefMut};
use core::marker::PhantomData;
use core::ops::{Deref, DerefMut};
use std::collections::HashMap;
use std::ffi::CString;

use crate::error::{BorrowError, Error, Result};
use crate::ffi;
use crate::runtime::{Ctx, JsLifetime};
use crate::value::{Constructor, FromJs, IntoJs, Object, Value};

/// No-op GC tracing hook kept for source compatibility with rquickjs
/// (`impl<'js> Trace<'js> for T { fn trace(&self, _: Tracer<'_, 'js>) {} }`).
/// Values held by a class instance are protected individually, so nothing
/// needs tracing — but that also means a cycle through Rust-held handles is
/// never collected.
pub trait Trace<'js> {
    fn trace<'a>(&self, tracer: Tracer<'a, 'js>);
}

#[derive(Clone, Copy)]
pub struct Tracer<'a, 'js>(PhantomData<(&'a (), &'js ())>);

impl<'js, T: Trace<'js>> Trace<'js> for &T {
    fn trace<'a>(&self, tracer: Tracer<'a, 'js>) {
        (**self).trace(tracer)
    }
}
impl<'js, T: Trace<'js>> Trace<'js> for Option<T> {
    fn trace<'a>(&self, tracer: Tracer<'a, 'js>) {
        if let Some(v) = self {
            v.trace(tracer)
        }
    }
}
impl<'js, T: Trace<'js>> Trace<'js> for Vec<T> {
    fn trace<'a>(&self, tracer: Tracer<'a, 'js>) {
        self.iter().for_each(|v| v.trace(tracer))
    }
}
impl<'js, T: Trace<'js>> Trace<'js> for Box<T> {
    fn trace<'a>(&self, tracer: Tracer<'a, 'js>) {
        (**self).trace(tracer)
    }
}
macro_rules! trace_noop {
    ($($t:ty),*) => {$(impl<'js> Trace<'js> for $t { fn trace<'a>(&self, _tracer: Tracer<'a, 'js>) {} })*};
}
trace_noop!((), bool, i8, i16, i32, i64, u8, u16, u32, u64, usize, isize, f32, f64, char, std::string::String);
impl<'js> Trace<'js> for Value<'js> {
    fn trace<'a>(&self, _tracer: Tracer<'a, 'js>) {}
}
impl<'js> Trace<'js> for Object<'js> {
    fn trace<'a>(&self, _tracer: Tracer<'a, 'js>) {}
}
impl<'js> Trace<'js> for crate::Function<'js> {
    fn trace<'a>(&self, _tracer: Tracer<'a, 'js>) {}
}
impl<'js> Trace<'js> for crate::Array<'js> {
    fn trace<'a>(&self, _tracer: Tracer<'a, 'js>) {}
}
impl<'js> Trace<'js> for crate::String<'js> {
    fn trace<'a>(&self, _tracer: Tracer<'a, 'js>) {}
}
impl<'js> Trace<'js> for crate::Promise<'js> {
    fn trace<'a>(&self, _tracer: Tracer<'a, 'js>) {}
}
impl<'js, C> Trace<'js> for Class<'js, C> {
    fn trace<'a>(&self, _tracer: Tracer<'a, 'js>) {}
}

/// Whether instances can be borrowed mutably.
pub trait Mutability: 'static {
    const MUTABLE: bool;
}
/// Instances can only be borrowed immutably.
pub struct Readable;
/// Instances can be borrowed mutably.
pub struct Writable;
impl Mutability for Readable {
    const MUTABLE: bool = false;
}
impl Mutability for Writable {
    const MUTABLE: bool = true;
}

/// Name of a class, generated by `#[rbun::class]`.
pub trait JsClassName {
    const NAME: &'static str;
}

/// Mutability of a class, generated by `#[rbun::class]` (`frozen` →
/// [`Readable`]).
pub trait ClassMutability {
    type Mutable: Mutability;
}

/// Constructor return: `C` or `Result<C>`.
pub trait IntoClassResult<C> {
    fn into_class_result(self) -> Result<C>;
}
impl<C> IntoClassResult<C> for C {
    fn into_class_result(self) -> Result<C> {
        Ok(self)
    }
}
impl<C> IntoClassResult<C> for Result<C> {
    fn into_class_result(self) -> Result<C> {
        self
    }
}

/// A type exposable as a JavaScript class.
pub trait JsClass<'js>: Trace<'js> + JsLifetime<'js> + Sized {
    const NAME: &'static str;

    /// [`Readable`] or [`Writable`].
    type Mutable: Mutability;

    /// The prototype instances get; `None` for `Object.prototype`.
    fn prototype(ctx: &Ctx<'js>) -> Result<Option<Object<'js>>> {
        Ok(Some(Object::new(*ctx)?))
    }

    /// The class constructor; `None` when the class cannot be constructed
    /// from JavaScript.
    fn constructor(_ctx: &Ctx<'js>) -> Result<Option<Constructor<'js>>> {
        Ok(None)
    }
}

fn class_type_id<'js, C: JsClass<'js> + 'js>() -> TypeId {
    TypeId::of::<C::Changed<'static>>()
}

// ─── Instances ───────────────────────────────────────────────────────────

/// `repr(C)` so `type_id` is at offset 0 for the type-erased check in
/// `instance_cell`.
#[repr(C)]
struct ClassCell<C> {
    #[allow(dead_code)] // read through a raw cast in `instance_cell`
    type_id: TypeId,
    cell: RefCell<C>,
}

unsafe extern "C" fn finalize_trampoline(object: ffi::JSObjectRef) {
    // SAFETY: private data was set by `make_instance`.
    let data = unsafe { ffi::JSObjectGetPrivate(object) };
    if !data.is_null() {
        let drop_fn = INSTANCE_DROPS.with(|d| d.borrow().get(&(data as usize)).copied());
        if let Some(drop_fn) = drop_fn {
            INSTANCE_DROPS.with(|d| d.borrow_mut().remove(&(data as usize)));
            // SAFETY: `drop_fn` was registered for exactly this allocation.
            unsafe { drop_fn(data) };
        }
        // SAFETY: live object.
        unsafe { ffi::JSObjectSetPrivate(object, core::ptr::null_mut()) };
    }
}

unsafe fn drop_cell<C>(data: *mut core::ffi::c_void) {
    // SAFETY: created via `Box::into_raw` in `make_instance`.
    drop(unsafe { Box::from_raw(data.cast::<ClassCell<C>>()) });
}

thread_local! {
    /// Private-data pointer → type-erased destructor (finalizers are plain
    /// C callbacks with no type information).
    static INSTANCE_DROPS: RefCell<HashMap<usize, unsafe fn(*mut core::ffi::c_void)>> = RefCell::new(HashMap::new());
    static CLASSES: RefCell<HashMap<TypeId, ClassEntry>> = RefCell::new(HashMap::new());
}

struct ClassEntry {
    class: ffi::JSClassRef,
    prototype: Option<ffi::JSValueRef>,
    constructor: Option<Option<ffi::JSValueRef>>,
}

fn class_ref<'js, C: JsClass<'js> + 'js>() -> ffi::JSClassRef {
    let id = class_type_id::<C>();
    if let Some(class) = CLASSES.with(|c| c.borrow().get(&id).map(|e| e.class)) {
        return class;
    }
    let class_name = CString::new(C::NAME).unwrap_or_else(|_| CString::new("Class").unwrap());
    let mut definition = ffi::JSClassDefinition::EMPTY;
    definition.class_name = class_name.as_ptr();
    definition.attributes = ffi::kJSClassAttributeNoAutomaticPrototype;
    definition.finalize = Some(finalize_trampoline);
    // SAFETY: fully initialised definition; JSC copies what it needs.
    let class = unsafe { ffi::JSClassCreate(&definition) };
    CLASSES.with(|c| c.borrow_mut().insert(id, ClassEntry { class, prototype: None, constructor: None }));
    class
}

fn instance_cell<'js, C: JsClass<'js> + 'js>(object: &Object<'js>) -> Option<&'js ClassCell<C>> {
    // SAFETY: live object.
    let data = unsafe { ffi::JSObjectGetPrivate(object.raw_object()) };
    if data.is_null() {
        return None;
    }
    if !INSTANCE_DROPS.with(|d| d.borrow().contains_key(&(data as usize))) {
        // Private data of some other JSC class.
        return None;
    }
    // SAFETY: registered instances are always `ClassCell<T>`; `type_id` is the
    // first field of every instantiation.
    let type_id = unsafe { *data.cast::<TypeId>() };
    if type_id != class_type_id::<C>() {
        return None;
    }
    // SAFETY: verified type; the cell lives as long as the (protected) object.
    Some(unsafe { &*data.cast::<ClassCell<C>>() })
}

fn make_instance<'js, C: JsClass<'js> + 'js>(ctx: Ctx<'js>, value: C, prototype: Option<&Object<'js>>) -> Result<Object<'js>> {
    let class = class_ref::<C>();
    let cell = Box::new(ClassCell { type_id: class_type_id::<C>(), cell: RefCell::new(value) });
    let data = Box::into_raw(cell).cast::<core::ffi::c_void>();
    INSTANCE_DROPS.with(|d| d.borrow_mut().insert(data as usize, drop_cell::<C>));
    // SAFETY: valid context; the class owns the finalizer that frees the
    // private data.
    let raw = unsafe { ffi::JSObjectMake(ctx.raw(), class, data) };
    // SAFETY: fresh object.
    let object = Object(unsafe { Value::from_raw(ctx, raw as ffi::JSValueRef) });
    if let Some(prototype) = prototype {
        object.set_prototype(Some(prototype))?;
    }
    Ok(object)
}

// ─── Class handle ────────────────────────────────────────────────────────

/// A JavaScript object backed by a Rust `C`.
pub struct Class<'js, C>(pub(crate) Object<'js>, PhantomData<C>);

impl<'js, C> Clone for Class<'js, C> {
    fn clone(&self) -> Self {
        Class(self.0.clone(), PhantomData)
    }
}

impl<'js, C> core::fmt::Debug for Class<'js, C> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "Class({:?})", self.0)
    }
}

impl<'js, C: JsClass<'js> + 'js> Class<'js, C> {
    /// Create an instance with the class prototype.
    pub fn instance(ctx: Ctx<'js>, value: C) -> Result<Class<'js, C>> {
        let prototype = Self::prototype(&ctx)?;
        let object = make_instance(ctx, value, prototype.as_ref())?;
        Ok(Class(object, PhantomData))
    }

    /// Create an instance with an explicit prototype.
    pub fn instance_proto(value: C, prototype: Object<'js>) -> Result<Class<'js, C>> {
        let ctx = *prototype.ctx();
        let object = make_instance(ctx, value, Some(&prototype))?;
        Ok(Class(object, PhantomData))
    }

    /// The class prototype (created once per runtime via
    /// [`JsClass::prototype`]).
    pub fn prototype(ctx: &Ctx<'js>) -> Result<Option<Object<'js>>> {
        let id = class_type_id::<C>();
        class_ref::<C>();
        if let Some(Some(prototype)) = CLASSES.with(|c| c.borrow().get(&id).map(|e| e.prototype)) {
            // SAFETY: protected for the runtime's lifetime.
            return Ok(Some(Object(unsafe { Value::from_raw(*ctx, prototype) })));
        }
        let prototype = C::prototype(ctx)?;
        if let Some(prototype) = &prototype {
            // SAFETY: keep the prototype alive for the runtime's lifetime.
            unsafe { ffi::JSValueProtect(ctx.raw(), prototype.as_raw()) };
            CLASSES.with(|c| {
                if let Some(entry) = c.borrow_mut().get_mut(&id) {
                    entry.prototype = Some(prototype.as_raw());
                }
            });
        }
        Ok(prototype)
    }

    /// The class constructor (created once per runtime via
    /// [`JsClass::constructor`]).
    pub fn create_constructor(ctx: &Ctx<'js>) -> Result<Option<Constructor<'js>>> {
        let id = class_type_id::<C>();
        class_ref::<C>();
        if let Some(Some(constructor)) = CLASSES.with(|c| c.borrow().get(&id).map(|e| e.constructor)) {
            // SAFETY: protected for the runtime's lifetime.
            return Ok(constructor.map(|raw| Constructor(crate::Function(Object(unsafe { Value::from_raw(*ctx, raw) })))));
        }
        let constructor = C::constructor(ctx)?;
        if let Some(constructor) = &constructor {
            constructor.set_name(C::NAME)?;
            // SAFETY: keep the constructor alive for the runtime's lifetime.
            unsafe { ffi::JSValueProtect(ctx.raw(), constructor.as_raw()) };
        }
        CLASSES.with(|c| {
            if let Some(entry) = c.borrow_mut().get_mut(&id) {
                entry.constructor = Some(constructor.as_ref().map(|c| c.as_raw()));
            }
        });
        Ok(constructor)
    }

    /// Define the class constructor as `NAME` on `object` (typically the
    /// globals).
    pub fn define(object: &Object<'js>) -> Result<()> {
        let ctx = *object.ctx();
        if let Some(constructor) = Self::create_constructor(&ctx)? {
            object.set(C::NAME, constructor)?;
        }
        Ok(())
    }

    pub fn from_object(object: Object<'js>) -> Option<Class<'js, C>> {
        instance_cell::<C>(&object).is_some().then(|| Class(object, PhantomData))
    }

    pub fn from_value(value: Value<'js>) -> Option<Class<'js, C>> {
        value.into_object().and_then(Self::from_object)
    }

    fn cell(&self) -> &'js ClassCell<C> {
        instance_cell::<C>(&self.0).expect("Class handle without a class instance")
    }

    pub fn borrow<'a>(&'a self) -> Borrow<'a, 'js, C> {
        self.try_borrow().expect("Error borrowing class")
    }

    pub fn try_borrow<'a>(&'a self) -> Result<Borrow<'a, 'js, C>> {
        self.cell()
            .cell
            .try_borrow()
            .map(|r| Borrow(r, PhantomData))
            .map_err(|_| Error::ClassBorrow(BorrowError::AlreadyBorrowed))
    }

    pub fn borrow_mut<'a>(&'a self) -> BorrowMut<'a, 'js, C>
    where
        C: JsClass<'js, Mutable = Writable>,
    {
        self.try_borrow_mut().expect("Error borrowing class")
    }

    pub fn try_borrow_mut<'a>(&'a self) -> Result<BorrowMut<'a, 'js, C>>
    where
        C: JsClass<'js, Mutable = Writable>,
    {
        self.cell()
            .cell
            .try_borrow_mut()
            .map(|r| BorrowMut(r, PhantomData))
            .map_err(|_| Error::ClassBorrow(BorrowError::AlreadyBorrowed))
    }

    /// Whether this object is an instance of the class `D`.
    pub fn instance_of<D: JsClass<'js> + 'js>(&self) -> bool {
        instance_cell::<D>(&self.0).is_some()
    }

    /// Raw pointer to the Rust value.
    pub fn as_class_ptr(&self) -> *mut C {
        self.cell().cell.as_ptr()
    }

    pub fn as_object(&self) -> &Object<'js> {
        &self.0
    }

    pub fn into_object(self) -> Object<'js> {
        self.0
    }

    pub fn as_value(&self) -> &Value<'js> {
        self.0.as_value()
    }

    pub fn into_value(self) -> Value<'js> {
        self.0.into_value()
    }

    pub fn ctx(&self) -> &Ctx<'js> {
        self.0.ctx()
    }
}

impl<'js, C> Deref for Class<'js, C> {
    type Target = Object<'js>;
    fn deref(&self) -> &Object<'js> {
        &self.0
    }
}

/// Immutable borrow of a class instance.
pub struct Borrow<'a, 'js, C>(Ref<'a, C>, PhantomData<&'js ()>);
impl<C> Deref for Borrow<'_, '_, C> {
    type Target = C;
    fn deref(&self) -> &C {
        &self.0
    }
}

/// Mutable borrow of a class instance.
pub struct BorrowMut<'a, 'js, C>(RefMut<'a, C>, PhantomData<&'js ()>);
impl<C> Deref for BorrowMut<'_, '_, C> {
    type Target = C;
    fn deref(&self) -> &C {
        &self.0
    }
}
impl<C> DerefMut for BorrowMut<'_, '_, C> {
    fn deref_mut(&mut self) -> &mut C {
        &mut self.0
    }
}

impl<'js, C: JsClass<'js> + 'js> IntoJs<'js> for Class<'js, C> {
    fn into_js(self, _ctx: &Ctx<'js>) -> Result<Value<'js>> {
        Ok(self.into_value())
    }
}

impl<'js, C: JsClass<'js> + 'js> FromJs<'js> for Class<'js, C> {
    fn from_js(_ctx: &Ctx<'js>, value: Value<'js>) -> Result<Self> {
        let type_name = value.type_name();
        Class::from_value(value).ok_or_else(|| Error::new_from_js(type_name, C::NAME))
    }
}

impl<'js> Object<'js> {
    /// Convert into a class handle if this object is an instance of `C`.
    pub fn into_class<C: JsClass<'js> + 'js>(self) -> core::result::Result<Class<'js, C>, Self> {
        if instance_cell::<C>(&self).is_some() { Ok(Class(self, PhantomData)) } else { Err(self) }
    }

    pub fn as_class<C: JsClass<'js> + 'js>(&self) -> Option<&Class<'js, C>> {
        // SAFETY: `Class` is `(Object, PhantomData)`, layout-identical to `Object`.
        instance_cell::<C>(self).is_some().then(|| unsafe { &*(self as *const Object<'js> as *const Class<'js, C>) })
    }

    pub fn instance_of<C: JsClass<'js> + 'js>(&self) -> bool {
        instance_cell::<C>(self).is_some()
    }
}

/// Borrow the Rust instance behind `this` in a method implementation
/// (used by `#[rbun::methods]`).
pub fn with_instance<'js, C: JsClass<'js> + 'js, R>(this: &Value<'js>, f: impl FnOnce(&mut C) -> Result<R>) -> Result<R> {
    let ctx = *this.ctx();
    let object = this
        .as_object()
        .cloned()
        .ok_or_else(|| crate::Exception::throw_type(&ctx, &format!("expected `this` to be a {} instance", C::NAME)))?;
    let class = Class::<C>::from_object(object)
        .ok_or_else(|| crate::Exception::throw_type(&ctx, &format!("expected `this` to be a {} instance", C::NAME)))?;
    let cell = class.cell();
    let mut guard = cell.cell.try_borrow_mut().map_err(|_| Error::ClassBorrow(BorrowError::AlreadyBorrowed))?;
    f(&mut guard)
}

/// Builds the prototype for `#[rbun::methods]`: methods become functions on
/// the prototype object.
pub struct PrototypeBuilder<'js> {
    ctx: Ctx<'js>,
    prototype: Object<'js>,
}

impl<'js> PrototypeBuilder<'js> {
    pub fn new(ctx: &Ctx<'js>) -> Result<Self> {
        Ok(PrototypeBuilder { ctx: *ctx, prototype: Object::new(*ctx)? })
    }

    pub fn method<P, F>(self, name: &str, f: F) -> Result<Self>
    where
        F: crate::function::IntoJsFunc<'js, P> + 'js,
    {
        let function = crate::Function::new(self.ctx, f)?.with_name(name)?;
        self.prototype.set(name, function)?;
        Ok(self)
    }

    pub fn getter<P, F>(self, name: &str, f: F) -> Result<Self>
    where
        F: crate::function::IntoJsFunc<'js, P> + 'js,
    {
        self.prototype.prop(name, crate::object::Accessor::from(f).configurable().enumerable())?;
        Ok(self)
    }

    pub fn build(self) -> Object<'js> {
        self.prototype
    }
}
